### PR TITLE
Add search box

### LINKED ISSUE #4: Filter fields when adding a condition
It would be great to have a search box to filter the fields. Sometimes the list can get big and it's difficult for the user to find a specific field.

image

Having an input to filter would add a good improvement for the user's experience:

image

### PR DESCRIPTION
**Pull request by vsppedro**
Closes #4

Run ` npm start`, go to `http://localhost:3001/`. You will see something like this:

Screenshot from 2020-04-03 11-53-08

Type something, it should filter the list.

You can use the keyboard to navigate between the values ​​and select one using the enter.

To browse the second component, you must press TAB first after rendering.

### CODE REVIEW

**Comment by rfdavid** [comment]
It's seems something is breaking when you try to edit. For example, run the npm start and try click to edit at "Name" or any other previous field.

**Comment by vsppedro** [comment]
@rfdavid, can you take another look, please?

**Comment by rfdavid** [comment]
It seems the problem is when you click to add a new node and before the option disappears you click to edit an existing one. 

behaviour

**Comment by vsppedro** [comment]
Needs a correction in the layout, the scroll bar is hiding a bit from the search box: 

Screenshot from 2020-04-27 18-07-23

**Review by rfdavid — APPROVED** [review]

**Pull request merged**
